# Generated by Django 5.2 on 2025-05-23 10:57

import django.core.validators
import django.db.models.deletion
import jsonfield.fields
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('schoolImg', models.ImageField(default='Images/default_page.png', upload_to='School/School Image')),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('pincode', models.CharField(default=None, max_length=10)),
                ('school_workbook_list', models.TextField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('student_requests', models.ManyToManyField(blank=True, default=None, related_name='student_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher_requests', models.ManyToManyField(blank=True, default=None, related_name='teacher_requests', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, default=None, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=2)),
                ('studentImg', models.ImageField(default='Images/default_page.png', upload_to='Student/Student Image')),
                ('guardian_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('student_assignment_list', jsonfield.fields.JSONField(default=dict)),
                ('student_school', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Student_School', to='parentTeacherApp.schoolprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StudentProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('teacherImg', models.ImageField(default='Images/default_page.png', upload_to='Teacher/Teacher Image')),
                ('phone', models.CharField(max_length=20)),
                ('class_subject_map', jsonfield.fields.JSONField(default=dict)),
                ('assigment_map', jsonfield.fields.JSONField(default=dict)),
                ('teacher_workbook_list', models.TextField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('teacher_school', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_School', to='parentTeacherApp.schoolprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
