# Generated by Django 5.2 on 2025-07-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentTeacherApp', '0002_worksheet_remove_schoolprofile_school_workbook_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('standard', models.CharField(default=None, max_length=5, null=True)),
                ('subject', models.CharField(default=None, max_length=10, null=True)),
                ('assignment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parentTeacherApp.assignment')),
                ('belongs_to', models.ManyToManyField(blank=True, related_name='belongs_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worksheet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parentTeacherApp.worksheet')),
            ],
            options={
                'ordering': ('-time_stamp',),
            },
        ),
    ]
