# Generated by Django 5.2 on 2025-05-23 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentTeacherApp', '0002_alter_studentprofile_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_School', to='parentTeacherApp.schoolprofile'),
        ),
    ]
