# Generated by Django 5.2 on 2025-05-29 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentTeacherApp', '0003_alter_teacherprofile_teacher_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='students',
            field=models.ManyToManyField(blank=True, default=None, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
