# Generated by Django 5.2 on 2025-06-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentTeacherApp', '0005_alter_schoolprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='standard',
            field=models.CharField(max_length=5),
        ),
    ]
